modLoader="javafml" #mandatory
loaderVersion="[34,)" #mandatory
license="${mod_license_url}" #mandatory
issueTrackerURL="${mod_issues_url}" #optional

[[mods]] #mandatory
modId="oldswing" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
displayURL="${mod_url}" #optional
logoFile="${mod_logo}" #optional
authors="${mod_author}" #optional
description='''
${mod_description}
'''
